### ISSUE TITLE
HTPPS response: An AttributeValue may not contain an empty string for key

### ISSUE THREAD

**Issue by TerrificMao** [awslabs/lambda-apigateway-twilio-tutorial#1]
could you please check and review below? I have deployed the code on AWS platform and I make sure the lambda function is working.

<?xml version="1.0" encoding="UTF-8" ?>
<Response>
<Message>
<Body>  
    {stackTrace=[
    ["\/var\/task\/lambda_function.py",32,"lambda_handler","response_dynamo = table_users.query(KeyConditionExpression=Key('fromNumber').eq(from_number))"],
    ["\/var\/runtime\/boto3\/resources\/factory.py",394,"do_action","response = action(self, _args, *_kwargs)"],
    ["\/var\/runtime\/boto3\/resources\/action.py",77,"**call**","response = getattr(parent.meta.client, operation_name)(**params)"],
    ["\/var\/runtime\/botocore\/client.py",310,"_api_call","return self._make_api_call(operation_name, kwargs)"],
    ["\/var\/runtime\/botocore\/client.py",395,"_make_api_call","raise ClientError(parsed_response, operation_name)"]], errorType=ClientError, errorMessage=An error occurred (ValidationException) when calling the Query operation: ExpressionAttributeValues contains invalid value: One or more parameter values were invalid: An AttributeValue may not contain an empty string for key :v0}
</Body>
</Message>
</Response>

**Comment by sunilmallya** [comment]
Seems like your variable fromNumber was empty.
